# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.177.0/containers/python-3/.devcontainer/base.Dockerfile
FROM mcr.microsoft.com/vscode/devcontainers/python:0-3.7

# Install/upgrade build and twine
RUN python3 -m pip install --upgrade \
    build \
    twine
