name: Build
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: lucas_env
    strategy:
      matrix:
       include:
        - python-version: "3.7"
          python-version-str: "py37"
        - python-version: "3.8"
          python-version-str: "py38"
        - python-version: "3.9"
          python-version-str: "py39"
        - python-version: "3.10"
          python-version-str: "py310"
        - python-version: "3.11"
          python-version-str: "py311"
    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.python-version-str }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Black
        run: |
          python -m pip install black
          black --check --diff src tests
      - name: Install dependencies, for extras and tests too
        run: |
          python -m pip install --upgrade pip
          pip install .[tests,azureblob,azuretable,gcpstorage,awss3]
      - name: Test with black and pytest
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_BLOB_STORAGE_ACCOUNT_URL: ${{ secrets.AZURE_BLOB_STORAGE_ACCOUNT_URL }}
          AZURE_BLOB_STORAGE_HIERARCHICAL_ACCOUNT_URL: ${{ secrets.AZURE_BLOB_STORAGE_HIERARCHICAL_ACCOUNT_URL }}
          AZURE_TABLE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_TABLE_STORAGE_CONNECTION_STRING }}
          GCP_CREDENTIALS_BASE64: ${{ secrets.GCP_CREDENTIALS_BASE64 }}
          GOOGLE_APPLICATION_CREDENTIALS: gcp.json
          GOOGLE_CLOUD_STORAGE_PROJECT: ${{ secrets.GOOGLE_CLOUD_STORAGE_PROJECT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo $GCP_CREDENTIALS_BASE64 | base64 -d > gcp.json
          pytest --test_container_id "${GITHUB_SHA::8}${{ matrix.python-version-str }}"