name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: lucas_env
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Black
        run: |
          python -m pip install black
          black --check --diff src tests
      - name: Install dependencies, for extras and tests too
        run: |
          python -m pip install --upgrade pip
          pip install .[tests,azure,gcp,aws]
      - name: Test with black and pytest
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          GCP_CREDENTIALS_BASE64: ${{ secrets.GCP_CREDENTIALS_BASE64 }}
          GOOGLE_APPLICATION_CREDENTIALS: gcp.json
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo $GCP_CREDENTIALS_BASE64 | base64 -d > gcp.json
          pytest \
            --azure_storage_account_url https://cloudmappingtests.blob.core.windows.net/ \
            --gcp_project cloud-mappings-test \
            --aws \
            --test_container_id ${GITHUB_SHA::6}