name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Upgrade build package
        run: python3 -m pip install --user --upgrade build
      - name: Run build
        run: python3 -m build
      - name: Upload output dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*
